[project]
name = 'b-btc-pepe'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = [{contrad_id="SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v5"}, 
{contract_id="SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v7"},
{contract_id="SP1Z92MPDQEWZXW36VX71Q25HKF5K2EPCJ304F275.tokensoft-token-v4k68639zxz"},
{contract_id="SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token"},
{contract_id="SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.bitcoin-helper-wtx-v1"},
{contract_id="SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1"},
{contract_id="SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.dexterity-traits-v0"},
{contract_id="SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-helper"}]
[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 2
epoch = 3.1

[contracts.styx-v4]
path = 'contracts/styx-v4.clar'
clarity_version = 2
epoch = 3.1


[repl.analysis]
passes = ['check_checker']



[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
